# Generated by Django 4.2.7 on 2023-11-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendCV.company'),
        ),
    ]
