# Generated by Django 4.2.7 on 2023-11-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='core_id',
            new_name='core',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
