# Generated by Django 4.2.7 on 2023-11-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0004_alter_company_id_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
