# Generated by Django 4.2.7 on 2023-11-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id_position', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='profile',
        ),
        migrations.RenameField(
            model_name='core',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='core',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='id',
            new_name='id_department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='position',
            name='cores_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.core'),
        ),
        migrations.AddField(
            model_name='position',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendCV.position'),
        ),
    ]
