# Generated by Django 4.2.1 on 2023-11-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hola', max_length=50),
        ),
    ]
