# Generated by Django 4.2.1 on 2023-11-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0007_position_remove_role_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendCV.position'),
        ),
    ]
