# Generated by Django 4.2.1 on 2023-11-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0009_alter_user_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.position'),
        ),
    ]
