# Generated by Django 4.2.7 on 2023-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0010_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='hola', max_length=50, unique=True),
        ),
    ]
