# Generated by Django 4.2.7 on 2023-11-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0010_alter_user_position_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='core',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
