# Generated by Django 4.2.7 on 2023-11-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0011_remove_employee_company_id_alter_core_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cell', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('ruc', models.CharField(max_length=13)),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('date_of_issue', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.client')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.invoice')),
            ],
        ),
    ]
