# Generated by Django 4.2.7 on 2023-11-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0013_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id_expense', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('made_by', models.CharField(max_length=40)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.expense_status')),
            ],
        ),
    ]
