# Generated by Django 4.2.7 on 2023-12-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0015_rename_expense_status_expensestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=255)),
                ('portfolio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsService',
            fields=[
                ('details_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('item', models.IntegerField()),
                ('detail', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('proforma_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=255)),
                ('prepared_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celphone_number', models.CharField(max_length=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('personnel', models.CharField(max_length=255)),
                ('work_time', models.CharField(max_length=255)),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('investment', models.TextField()),
                ('package', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentConditions',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('deposits', models.CharField(max_length=255)),
                ('payable_to', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('cci', models.CharField(max_length=255)),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.project')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('characteristics_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_1', models.CharField(max_length=255)),
                ('package_2', models.CharField(max_length=255)),
                ('package_3', models.CharField(max_length=255)),
                ('details_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.detailsservice')),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.proforma')),
            ],
        ),
    ]
