# Generated by Django 4.2.7 on 2023-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0016_company_detailsservice_proforma_project_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
