# Generated by Django 4.2.7 on 2023-12-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0017_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_employees', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=12)),
                ('id_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.position')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('proforma_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=255)),
                ('prepared_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('work_time', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('requered_by', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.company')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.employees')),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note_price', models.CharField(max_length=255)),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.items')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.packages')),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendCV.proforma')),
            ],
        ),
    ]
