# Generated by Django 4.2.7 on 2023-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0018_areas_employees_items_proforma_personalproyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='id_employees',
            new_name='employee_id',
        ),
    ]
