# Generated by Django 4.2.7 on 2023-12-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0019_rename_id_employees_employees_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='portfolio',
            new_name='category',
        ),
    ]
