# Generated by Django 4.2.7 on 2023-12-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0020_rename_portfolio_company_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
